### ISSUE TITLE
vcr: do not record the storage account keys

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-python-devtools#48]
Sample recording content: 

```yaml
- request:
    body: null
    headers:
      Accept: [application/json]
      Accept-Encoding: ['gzip, deflate']
      CommandName: [functionapp create]
      Connection: [keep-alive]
      Content-Length: ['0']
      Content-Type: [application/json; charset=utf-8]
      User-Agent: [python/3.5.4 (Windows-10-10.0.16299-SP0) requests/2.18.4 msrest/0.4.29
          msrest_azure/0.4.29 azure-mgmt-storage/1.5.0 Azure-SDK-For-Python AZURECLI/2.0.33]
      accept-language: [en-US]
    method: POST
    uri: https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.Storage/storageAccounts/functionappplanstorage/listKeys?api-version=2017-10-01
  response:
    body: {string: '{"keys":[{"keyName":"key1","value":"...","permissions":"FULL"},{"keyName":"key2","value":"...","permissions":"FULL"}]}'}

```
